package com.attendance.office

class AppConstant {
    companion object{
        val CAPTURING_LAT_LONG :String = "Please wait capturing location"
        val PRESS_ONCE: String ="Please click BACK again to exit"
        val ANDROID: String ="Android "
        val  EMP_ID :String="emp_id"
        val EMP_MAIL: String  = "emp_mail"
        val VALID_MAIL: String  = "Please enter valid mail"
        val VALID_PASS: String  = "Please length not match"
        val VALID_ID: String  = "Please enter valid id"
        val VALID_PHONE: String  = "Please enter valid number"
        val VALID_DESIGNATION: String  = "Please enter designation"
        val VALID_DEPARTMENT: String  = "Please enter department"
        val VALID_GENDER: String  = "Please enter gender"
        val ADHAAR_ID: String  = "Please enter valid adhaar number"
        val IMAGE_UPLOAD: String  = "Please upload your image"
        val MARKIN: String  = "markIn"
        val MARKOUT: String  = "markOut"
        val LOGOUT: String  = "is_from_logout"
        val VALID_NAME: String  = "Please enter name"
        val VALID_LAST_NAME: String  = "Please enter last name"

        /*add employee*/
        val FIRST_NAME  = "first_name"
        val LAST_NAME = "last_name"
        val EMP_CODE = "emp_id"
        val EMP_MAILID = "email"
        val EMP_DEPARTMENT = "department"
        val EMP_DESIGNATION = "designation"
        val EMP_PHONE = "contact"
        val GENDER = "gender"
        val PASSWORD  = "password"
        val AADHAR_NUMBER = "aadhar"
        val IMAGE_URL = "image_url"

        val EMAIL = "email"
        val PASSWORD_LOGIN = "password"
        val INVALID = "Invalid"
        val NETWORK_NOT_AVAILABLE = "Network not available"
        val ADDED = "Successfully Added"
        val SOMETHING_WENT_WRONG = "something went wrong"
        val UNKNOWN ="unknown"
        val ATTDATE = "attdate"
        val SIGN_IN = "signin"
        val SIGN_OUT = "signout"
        val PLACE ="place"
        val BLANK = ""
        val MARKED_IN_SUCCESSFULLY = "Marked in successfully"
        val MARKED_OUT_SUCCESSFULLY = "Marked out successfully"
        val SUCCESS = "Successfully added."
        val SUCCESSFULLY = "Successfully"
        val SUCCESS_UPDATED = "Successfully updated."
        val IMAGE_BITMAP = "IMAGE_BITMAP"
        val SUCCESSFULLY_AUTHENTICATE ="Successfuly Authenticate"
        val FAILED_AUTHENTICATE ="Failed to Authenticate"
        val MARK_IN_ID ="id"
        val MARK_IN_PLACE ="place"
        val MARK_OUT_PLACE ="signout_place"
        val BASE_URL = "http://ec2-52-66-155-64.ap-south-1.compute.amazonaws.com/edlhrms/api/public/"

        val ACTION ="action"
        val LATLONG ="latlong"
        val ADDRESS_MARK ="address"
        val NOTE ="note"
        val PUNCH_IN ="PUNCHIN"
        val PUNCH_REQUEST ="Punch Request"
        val PUNCH_OUT ="PUNCHOUT"
        val RESPONSE_SUCCESS ="success"
    }
}